package:
    name: pcmdi_metrics
    version: {{ environ['VERSION'] }}

source:
    git_url: git://github.com/PCMDI/pcmdi_metrics

build:
    number: 0
    script: python setup.py install
    script_env:
     - VERSION
     - CONDA_BLD_PATH


requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - vcs >=2.6
    - vcsaddons
    - cdms2 >2.6
    - genutil
    - cdutil
    - unidata
    - cdp
    - matplotlib
    - numpy

about:
    home:  http://gitub.com/PCMDI/pcmdi_metrics
    summary: The PCMDI metrics package is used to objectively compare results from climate models with observations using well-established statistical tests. Results are produced in the context of all model simulations contributed to CMIP5 and earlier CMIP phases. Among other purposes, this enables modeling groups to evaluate changes during the development cycle in the context of the structural error distribution of the multi-model ensemble. Currently, the comparisons are focused on large- to global-scale annual cycle performance metrics.
